#!/usr/bin/env sh

sudo add-apt-repository ppa:brightbox/ruby-ng-experimental
sudo apt-get update
sudo apt-get install -y ruby2.0 ruby2.0-dev ruby2.0-doc

for package in `cat ~/DotFiles/Ruby/gem`; do
    echo INSTALL : $package
    sudo gem install $package --no-ri --no-rdoc >> /dev/null
done
