#!/bin/bash

cd ~/DotFiles
git pull origin master >> /dev/null
cd - >> /dev/null

sh ~/DotFiles/install_exec

cd ~ >> /dev/null
source ~/DotFiles/Symlink/bashrc >> /dev/null
cd - >> /dev/null

ponysay "That's all dude !"
