#!/bin/bash

sh ~/DotFiles/symlink
sh ~/DotFiles/WorkSpace/install
sh ~/DotFiles/Config/install
sh ~/DotFiles/Apt/install
sh ~/DotFiles/Firefox/install
sh ~/DotFiles/Ruby/install
sh ~/DotFiles/NodeJs/install
sh ~/DotFiles/Composer/install
sh ~/DotFiles/Vim/install
sh ~/DotFiles/Powerline/install
sh ~/DotFiles/Apache/install
sh ~/DotFiles/Selenium/install
sh ~/DotFiles/WkHtmlToPDF/install
sh ~/DotFiles/BTSync/install

cd ~ >> /dev/null
source ~/DotFiles/Symlink/bashrc >> /dev/null
cd - >> /dev/null

ponysay "That's all dude !"
