#!/bin/bash

sh ~/DotFiles/symlink
sh ~/DotFiles/Apt/install
sh ~/DotFiles/Vim/plugin-install
sh ~/DotFiles/Powerline/install

cd ~ >> /dev/null
source ~/DotFiles/Symlink/bashrc >> /dev/null
cd - >> /dev/null
