#!/bin/bash

sh ~/DotFiles/symlink
sh ~/DotFiles/WorkSpace/install
sh ~/DotFiles/SSH/install
sh ~/DotFiles/Config/install
sh ~/DotFiles/MysqlServer/install
sh ~/DotFiles/Apt/install
sh ~/DotFiles/Ruby/install
sh ~/DotFiles/NodeJs/install
sh ~/DotFiles/Composer/install
sh ~/DotFiles/Vim/install
sh ~/DotFiles/Powerline/install
sh ~/DotFiles/Apache/install
sh ~/DotFiles/VHosts/install
sh ~/DotFiles/Selenium/install
sh ~/DotFiles/PhantomJs/install
sh ~/DotFiles/WkHtmlToPDF/install
sh ~/DotFiles/BTSync/install
