#!/bin/bash

sh ~/DotFiles/symlink
sh ~/DotFiles/WorkSpace/install
sh ~/DotFiles/Tools/install
sh ~/DotFiles/SSH/install
sh ~/DotFiles/Config/install
sh ~/DotFiles/Pacman/install
sh ~/DotFiles/Pear/install
sh ~/DotFiles/Vim/install
sh ~/DotFiles/Powerline/install
sh ~/DotFiles/Hub/install
