#!/bin/bash

alias nano="vim"
alias node="nodejs"
alias symfony='teamocil symfony'
alias phplib='teamocil php'
alias sinit='sudo setfacl -R -m u:www-data:rwX -m u:`whoami`:rwX app/cache app/logs ; sudo setfacl -dR -m u:www-data:rwx -m u:`whoami`:rwx app/cache app/logs ; cacl'
alias selenium="phantomjs --webdriver=4444"
alias tmux='tmux -2'
alias cacl='sf cache:clear'
alias rode='sf ro:de'
alias contde='sf cont:de'
alias nyan='phpspec --format=nyan'
alias g='git'
alias gs='git status'
alias gb='git branch'
alias gc='git commit'
alias gps='git push'
alias gpu='git pull'
alias gck='git checkout'
alias gcl='git clone'
alias gpurge='git branch --merged master | grep -v master | xargs git branch -d'
alias log="git log --graph --pretty=format:'%Cred%h %Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
alias :q="exit"
alias :e="vim"
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ..="cd .."
alias .="cd ."
alias ~="cd ~"
alias xflock4="~/Tools/lock"
alias sfctags="ctags -R ./src app/AppKernel.php ./vendor ./features ./spec"
alias fix="php-cs-fixer --config-file=~/.php_cs fix"
alias tmuxify="teamocil --layout=./.teamocil.yml"
