#!/bin/bash

alias nano="vim"
alias node="nodejs"
alias symfony='teamocil symfony'
alias phplib='teamocil php'
alias sinit='sudo setfacl -R -m u:www-data:rwX -m u:`whoami`:rwX app/cache app/logs ; sudo setfacl -dR -m u:www-data:rwx -m u:`whoami`:rwx app/cache app/logs ; cacl'
alias selenium="phantomjs --webdriver=4444"
alias tmux='tmux -2'
alias nyan='phpspec --format=nyan'
alias git="hub"
alias g='git'
alias gs='git status'
alias gb='git branch'
alias gc='git commit'
alias gps='git push'
alias gpu='git pull'
alias gck='git checkout'
alias gcl='git clone'
alias gpurge='git branch --merged | grep -v master | grep -v develop | xargs git branch -d'
alias log="git log --graph --pretty=format:'%Cred%h %Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
alias :q="exit"
alias :e="vim"
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ..="cd .."
alias .="cd ."
alias ~="cd ~"
alias xflock4="~/Tools/lock"
alias sfctags="ctags -R ./src app/AppKernel.php ./vendor ./features ./spec"
alias fix="php-cs-fixer --config-file=~/.php_cs fix"

# SYMFONY

alias cacl='sf cache:clear'
alias rode='sf debug:router'
alias contde='sf debug:container'

# DOCKER

alias docker-top="docker run -ti -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop:latest"
alias docker-purge='docker stop $(docker ps -q -a) && docker rm -vf $(docker ps -q -a) && docker rmi -f $(docker images -q) && docker network rm $(docker network ls -q)'
