# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard 'ctags-composer', :src_path => ["src"], :vendor_path => ["vendor"] do
  watch(/^(src|tests)\/.*\.php$/)
  watch('composer.lock')
end
