#!/bin/bash

cd ~/Tools >> /dev/null

sudo rm /usr/bin/btsync -f

if [ `getconf LONG_BIT` = "64" ]; then
    wget https://download-cdn.getsyncapp.com/stable/linux-x64/BitTorrent-Sync_x64.tar.gz --output-document=btsync.tar.gz >> /dev/null
else
    wget https://download-cdn.getsyncapp.com/stable/linux-i386/BitTorrent-Sync_i386.tar.gz --output-document=btsync.tar.gz >> /dev/null
fi

tar -zxvf btsync.tar.gz >> /dev/null
sudo ln -s Tools/btsync /usr/bin/btsync >> /dev/null

rm btsync.tar.gz -f

cd - >> /dev/null
