#!/bin/bash

cd ~/Tools >> /dev/null

sudo rm /usr/bin/resilio -f

if [ `getconf LONG_BIT` = "64" ]; then
    wget https://download-cdn.resilio.com/stable/linux-x64/resilio-sync_x64.tar.gz --output-document=resilio.tar.gz >> /dev/null
else
    wget https://download-cdn.resilio.com/stable/linux-i386/resilio-sync_i386.tar.gz --output-document=resilio.tar.gz >> /dev/null
fi

tar -zxvf resilio.tar.gz >> /dev/null
sudo ln -s Tools/rslsync /usr/bin/rslsync >> /dev/null

rm resilio.tar.gz -f

cd - >> /dev/null
