#!/bin/bash

if [ ! -f /etc/apache2/server.crt ]
then
    sudo openssl req -x509 -nodes -days 365 -newkey rsa:1024 -out /etc/apache2/server.crt -keyout /etc/apache2/server.key
    sudo chmod o-rw /etc/apache2/server.key
fi

sudo rm -rf /etc/apache2/site-enabled/*
sudo php ~/DotFiles/VHosts/install.php
sudo service apache2 restart
