#!/usr/bin/env sh

sudo apt-get autoremove nodejs -y >> /dev/null
sudo apt-get install python-software-properties -y >> /dev/null
sudo add-apt-repository ppa:chris-lea/node.js -y >> /dev/null
sudo apt-get update -y >> /dev/null
sudo apt-get install nodejs -y >> /dev/null
echo INSTALLATION : nodejs
nodejs --version

for package in `cat ~/DotFiles/NodeJs/npm`; do
    echo INSTALLATION : $package
    sudo npm install --global $package >> /dev/null
done
