#!/bin/bash

while file=$(inotifywait -r -e modify -e delete -e create -e move --format "%w%f" ./); do
    EXT=${file##*.}
    if [ $EXT = "php" ]
    then
        ctags -R ./src ./bin app/AppKernel.php ./vendor ./features ./spec --languages=php --exclude=*.js,*.html -f=php.all.tags -V
        echo "Done..."
    fi
done
