#!/usr/bin/php
<?php

list($me, $file) = $argv;

$content = file_get_contents($file);
$content = str_replace("\t", "    ", $content);
$content = explode("\n", $content);
$indent  = [];

foreach ($content as $line) {
    $indent[] = countSpaces($line);
}

$indent = array_unique($indent);
sort($indent);

if (2 > count($indent)) {

    exit;
}

$structure = [];
$base = '';
$current = '';

foreach ($content as $line) {
    if (empty(trim($line))) {

        continue;
    }
    switch (countSpaces($line)) {
        case $indent[0]:
            $base = $line;
            $structure[$base] = [];
            break;
        case $indent[1]:
            $current = $line;
            $structure[$base][$current] = [];
            break;
        default:
            $structure[$base][$current][] = $line;
            break;
    }
}

foreach($structure as $name => $content) {
    $a = $content;
    ksort($a);
    $structure[$name] = $a;
}

$content = '';

foreach ($structure as $name => $elements) {
    $content .= empty($content) ? '' : "\n";
    $content .= $name . "\n";

    foreach ($elements as $key => $values) {
        $content .= $key . "\n";
        foreach ($values as $value) {
            $content .= $value . "\n";
        }
        $content .= empty($values) ? '' : "\n";
    }
}

file_put_contents($file, $content);

function countSpaces($str)
{
    $cpt = 0;
    while (!empty($str) && ' ' === substr($str, 0, 1)) {
        $cpt++;
        $str = substr($str, 1);
    }

    return $cpt;
}
