#!/usr/bin/env sh

sudo add-apt-repository ppa:ondrej/php5 -y
sudo apt-get update
sudo apt-get install php5 -y

sudo rm -rf /etc/php5/cli/php.ini
sudo ln -s /etc/php5/apache2/php.ini /etc/php5/cli/php.ini
    
sudo ~/Tools/configure /etc/php5/cli/php.ini memory_limit 2048M >> /dev/null
sudo ~/Tools/configure /etc/php5/cli/php.ini xdebug.max_nesting_level 20000 >> /dev/null
sudo ~/Tools/configure /etc/php5/cli/php.ini date.timezone "Europe/Paris" >> /dev/null
sudo ~/Tools/configure /etc/php5/cli/php.ini short_open_tag Off >> /dev/null
sudo ~/Tools/configure /etc/php5/cli/php.ini "extension=mongo.so" >> /dev/null
