#!/usr/bin/php
<?php

$confFile = null;
$binary   = null;

exec('git rev-parse --show-toplevel', $root);

$possibleConfig = array(
    sprintf('%s/.php_cs', getcwd()),
    sprintf('%s/.php_cs', '.'),
    sprintf('%s/.php_cs', current($root)),
    sprintf('%s/.php_cs.dist', getcwd()),
    sprintf('%s/.php_cs.dist', '.'),
    sprintf('%s/.php_cs.dist', current($root)),
);

$possibleConfig = array_unique($possibleConfig);

foreach ($possibleConfig as $file) {
    if (null === $confFile && true === file_exists($file)) {
        $confFile = $file;
    }
}

if (null === $confFile) {
    exit(0);
}

$possibleBinaries = array(
    sprintf('%s/php-cs-fixer', getcwd()),
    sprintf('%s/php-cs-fixer', '.'),
    sprintf('%s/php-cs-fixer', current($root)),
);

$possibleBinaries = array_unique($possibleBinaries);

foreach ($possibleBinaries as $file) {
    if (null === $binary && true === file_exists($file)) {
        $binary = $file;
    }
}

if (null === $binary) {
    $binary = 'php-cs-fixer';
}

exec('git diff --cached --name-status --diff-filter=ACM', $output);

foreach ($output as $file) {
    $fileName = trim(substr($file, 1) );
    if (pathinfo($fileName,PATHINFO_EXTENSION) == "php") {
        $lint_output = array();
        exec("php -l " . escapeshellarg($fileName), $lint_output, $return);
        if ($return == 0) {
            exec("{$binary} fix {$fileName} --config-file=\"{$confFile}\"; git add {$fileName}");
        } else {
            echo implode("\n", $lint_output), "\n";

            exit(1);
        }
    }
}

exit(0);
